doks:
    baseurl: /lunacy-docs
    color_theme: blue
    header:
        logo:
            text: Lunacy
            image:
        nav:
            - item_name: Release Notes
              item_url: '/release-notes'
            
    footer:
        content:
            logo:
                text: Lunacy
                image:
            copyright: Copyright &copy; 2018. - icons8 <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/icons8/lunacy-docs'

    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
